Work-Around: I/O w/ GCC 8.3 (#3943)
Up to GCC 8.3, severe bugs skipping required copy elision are present.
Apply work-arounds for issues seen on Lassen (LLNL).

```
Source/Diagnostics/WarpXOpenPMD.cpp(543): error: function "NamedComponentParticleContainer<T_Allocator>::operator=(const NamedComponentParticleContainer<T_Allocator> &) [with T_Allocator=amrex::PinnedArenaAllocator]"
Source/Particles/NamedComponentParticleContainer.H(100): here cannot be referenced -- it is a deleted function

Source/Diagnostics/WarpXOpenPMD.cpp(545): error: function "NamedComponentParticleContainer<T_Allocator>::operator=(const NamedComponentParticleContainer<T_Allocator> &) [with T_Allocator=amrex::PinnedArenaAllocator]"
Source/Particles/NamedComponentParticleContainer.H(100): here cannot be referenced -- it is a deleted function

2 errors detected in the compilation of "Source/Diagnostics/WarpXOpenPMD.cpp".
...

Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp(345): error: function "NamedComponentParticleContainer<T_Allocator>::operator=(const NamedComponentParticleContainer<T_Allocator> &) [with T_Allocator=amrex::PinnedArenaAllocator]"
Source/Particles/NamedComponentParticleContainer.H(100): here cannot be referenced -- it is a deleted function

...
Source/Particles/ParticleBoundaryBuffer.cpp(228): error: function "NamedComponentParticleContainer<T_Allocator>::operator=(const NamedComponentParticleContainer<T_Allocator> &) [with T_Allocator=amrex::PinnedArenaAllocator]"
Source/Particles/NamedComponentParticleContainer.H(100): here cannot be referenced -- it is a deleted function

1 error detected in the compilation of "Source/Particles/ParticleBoundaryBuffer.cpp".
```

(Implementing the copy operator does not help.)