CI: Windows (#1521)
* CI: Windows

Add an MSVC build to CI.

* Windows: _USE_MATH_DEFINES

Fix:
```
error C2065: 'M_PI': undeclared identifier
```

* Windows: no unistd.h

fix:
```
fatal error C1083: Cannot open include file: 'unistd.h':
No such file or directory
```

* Injector: Trivially Copyable only GPU

Only strictly required when we memcopy to accelerator devices.

* Flex: never-interactive

We don't use the interactive mode, so we can save some performance
and address:
```
Parser\wp_parser.lex.cpp(1503,40): error C3861: 'isatty': identifier not found
```

Alternatively, we can include `<io.h>` on Windows.

* MSVC: Vector<Long> != Vector<long>

Fix return and assignment issues with `amrex::Long` != `long`
in `amrex::Vector`.

```
  Particles\MultiParticleContainer.cpp(438,13): error C2440: 'return': cannot convert from 'const amrex::Vector<amrex::Long,std::allocator<__int64>>' to 'amrex::Vector<long,std::allocator<long>>'
  Particles\MultiParticleContainer.cpp(452,94): error C2440: 'initializing': cannot convert from 'amrex::Vector<amrex::Long,std::allocator<__int64>>' to 'amrex::Vector<long,std::allocator<long>>'
  Particles\MultiParticleContainer.cpp(459,60): error C2665: 'amrex::ParallelDescriptor::ReduceLongSum': none of the 6 overloads could convert all the argument types
  Particles\WarpXParticleContainer.cpp(782,51): error C2665: 'amrex::ParallelDescriptor::ReduceLongSum': none of the 6 overloads could convert all the argument types
```

* Windows CI: Parallel Build