CMake 3.20+ and CUDA: Modernized AMReX (#1998)
* CMake 3.20+ and CUDA: Modernized AMReX

Use modernized AMReX logic for CUDA builds with CMake 3.20+ as
supported by the latest AMReX updates.

* Resampling Trigger: Missing Include

AMReX update triggered missing include:
```
Source/Particles/Resampling/ResamplingTrigger.H(42):
error: namespace "amrex" has no member "Real"
```

* Update AMReX

Update AMReX to f7fd082bc8ab099d42784f69d6fe49dea3d388a7