Remove checksum values that cause false positives (#6750)
## Overview

- Do not write the particle momentum along "x" in the particle output of
the following two RZ tests, as they are typically numerical noise over
values that should be zero, leading to eccessively large relative errors
(e.g., $\sim 10^{-1}$), even without any code changes:
  - `test_rz_langmuir_multi_psatd`
  - `test_rz_langmuir_multi_psatd_current_correction`

- Add `skip_component` input argument to the functions
`check_particle_filter` and `check_random_filter` to allow skipping a
chosen component if it is not included in the ouput.

## To do 

- [x] Merge #6751 and rebase.

## Notes

Running the two RZ tests above on my local computer from a clean
`development` branch leads to the following checksum errors:
```
$ ctest --test-dir build --output-on-failure -R "test_rz_langmuir_multi_psatd\..*"
Test project /home/edoardo/src/warpx/build
    Start 40: test_rz_langmuir_multi_psatd.run
1/3 Test #40: test_rz_langmuir_multi_psatd.run ........   Passed    2.44 sec
    Start 41: test_rz_langmuir_multi_psatd.analysis
2/3 Test #41: test_rz_langmuir_multi_psatd.analysis ...   Passed    3.07 sec
    Start 42: test_rz_langmuir_multi_psatd.checksum
3/3 Test #42: test_rz_langmuir_multi_psatd.checksum ...***Failed    1.81 sec
ERROR: Benchmark and output file checksum have different value for key [ions,particle_momentum_x]
Benchmark: [ions,particle_momentum_x] 2.492077828060507e-36
Test file: [ions,particle_momentum_x] 3.178671888536597e-36
Absolute error: 6.87e-37
Relative error: 2.76e-01
ERROR: Benchmark and output file checksum have different value for key [electrons,particle_momentum_x]
Benchmark: [electrons,particle_momentum_x] 3.515712191296590e-36
Test file: [electrons,particle_momentum_x] 4.525673862189935e-36
Absolute error: 1.01e-36
Relative error: 2.87e-01

Maximum relative error: 2.87e-01
```
and
```
$ ctest --test-dir build --output-on-failure -R "test_rz_langmuir_multi_psatd_current_correction\..*"
Test project /home/edoardo/src/warpx/build
    Start 43: test_rz_langmuir_multi_psatd_current_correction.run
1/3 Test #43: test_rz_langmuir_multi_psatd_current_correction.run ........   Passed    4.06 sec
    Start 44: test_rz_langmuir_multi_psatd_current_correction.analysis
2/3 Test #44: test_rz_langmuir_multi_psatd_current_correction.analysis ...   Passed    3.08 sec
    Start 45: test_rz_langmuir_multi_psatd_current_correction.checksum
3/3 Test #45: test_rz_langmuir_multi_psatd_current_correction.checksum ...***Failed    1.77 sec
ERROR: Benchmark and output file checksum have different value for key [ions,particle_momentum_x]
Benchmark: [ions,particle_momentum_x] 1.497670208575471e-36
Test file: [ions,particle_momentum_x] 1.874813372893291e-36
Absolute error: 3.77e-37
Relative error: 2.52e-01
ERROR: Benchmark and output file checksum have different value for key [electrons,particle_momentum_x]
Benchmark: [electrons,particle_momentum_x] 3.372871939703005e-36
Test file: [electrons,particle_momentum_x] 3.344514244357131e-36
Absolute error: 2.84e-38
Relative error: 8.41e-03

Maximum relative error: 2.52e-01
```

Previous instances where these checksums values raised false positives
include:
- https://github.com/BLAST-WarpX/warpx/pull/3936 (see, in particular,
https://github.com/BLAST-WarpX/warpx/pull/3936#issuecomment-1557995919)
- https://github.com/BLAST-WarpX/warpx/pull/6615