CI: fix IntelLLVM builds (#5419)
The CI checks `Intel / oneAPI ICX SP` and `Intel / oneAPI DPC++ SP` are
failing since a few days.

This is likely due to the fact that the GitHub Actions runner is now
installing IntelLLVM 2025.0.0 instead of IntelLLVM 2024.2.1, as until a
few days ago.

This causes the following issue when building openPMD:
```console
/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedopenpmd-src/include/openPMD/backend/Container.hpp:263:32: error: no member named 'm_container' in 'Container<T, T_key, T_container>'
  263 |         container().swap(other.m_container);
      |                          ~~~~~ ^
1 error generated.
```

We can try to install the previous version of IntelLLVM manually and see
if that fixes the issue.